source "https://rubygems.org"

gem "github-pages", "~> 230", group: :jekyll_plugins
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-remote-theme"
  gem "jekyll-email-protect"
  gem "jekyll-inline-svg"
  gem "jekyll-loading-lazy"
  gem "jekyll-scholar", "~> 5.16.0"  # Version compatible avec Jekyll 3.9.5
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-timeago"
  gem "jekyll-toc"
  gem "jekyll-typogrify"
  gem "jemoji"
  gem "liquid_pluralize"
  gem "kramdown-parser-gfm"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# source "http://rubygems.org"
# # Hello! This is where you manage which Jekyll version is used to run.
# # When you want to use a different version, change it below, save the
# # file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
# #
# #     bundle exec jekyll serve --livereload
# #

# # Updated to more recent, compatible versions
# gem "jekyll", "~> 4.3.0"
# gem "github-pages", "~> 230", group: :jekyll_plugins
# gem "webrick", "~> 1.8"
# gem "sassc", "~> 2.4.0"

# # If you have any plugins, put them here!
# group :jekyll_plugins do
#   #gem "jekyll-sass-converter", "~> 3.0.0"
#   gem "jekyll-feed", "~> 0.17.0"
#   gem "jekyll-remote-theme"
#   gem "jekyll-email-protect"
#   gem "jekyll-inline-svg"
#   gem "jekyll-loading-lazy"
#   gem "jekyll-scholar", "~> 6.0.0"
#   gem "jekyll-seo-tag"
#   gem "jekyll-sitemap"
#   gem "jekyll-timeago"
#   gem "jekyll-toc"
#   gem "jekyll-typogrify"
#   gem "jemoji"
#   gem "liquid_pluralize"
#   gem "kramdown-parser-gfm" # Required for GitHub Flavored Markdown
# end

# # Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# # and associated library.
# platforms :mingw, :x64_mingw, :mswin, :jruby do
#   gem "tzinfo", ">= 1", "< 3"
#   gem "tzinfo-data"
# end

# # Performance-booster for watching directories on Windows
# gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# # Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# # do not have a Java counterpart.
# gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
